#!/usr/bin/env bash
# script that displays numbers from 1 to 100. when the numbers are multiple of an x number
c=0
while [[ $c -le 100 ]]; do
	
	if ((c % 15 == 0)); then
		echo FizzBuzz
	elif ((c % 3 == 0)); then
		echo Fizz
	elif ((c % 5 == 0)); then
		echo Buzz
	else
	echo $c	
fi
	(( c++ ))
done
