#!/usr/bin/env bash
#script that displays: The content of the current directory in a list format where only the part of the name after the first dash is displayed
list=$(ls)
for i in $list
do
	echo "$i" | cut -f2 -d-
done
