#!/usr/bin/env bash
#script that gives you information about the school file.
f=$(find)
if [ $f -e ]
then 
	echo school file exists
else
	echo school file does not exist
elif [ $f -s ]
	echo school file is not empty
else 
	echo school file is empty
elif [ $f -f ]
	echo school file is a regular file 
else
	echo " "
fi
