#!/usr/bin/env bash
#script that creates a file /var/run/myscript.pid containing its PID; Displays To infinity and beyond indefinitely; Displays I hate the kill command when receiving a SIGTERM signal; Displays Y U no love me?! when receiving a SIGINT signal; Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pid_file="/var/run/myscript.pid"
echo $$ > $pid_file
while [[ 4 -lt 5 ]]; do
  echo To infinity and beyond
  done
  if trap 15; then
    echo I hate the kill command
    elif trap 2; then 
    echo I U no love me?!
    elif trap 3,15; then 
    rm $pid_file
  fi
