#!/usr/bin/env bash
#script that creates a file /var/run/myscript.pid containing its PID; Displays To infinity and beyond indefinitely; Displays I hate the kill command when receiving a SIGTERM signal; Displays Y U no love me?! when receiving a SIGINT signal; Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pid_file="/var/run/myscript.pid"
echo $$ > $pid_file
while [[ 4 -lt 5 ]]; do
  echo To infinity and beyond
trap 15; echo I hate the kill command
trap 2; echo I U no love me?!
trap 3,15; rm $pid_file
done
