#!/usr/bin/env bash
#script 11-manage_my_process that manages manage_my_process
case $1 in
  start) 
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
  ;;
  stop)
    cat /var/run/my_process.pid | kill
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  ;;
  restart)
    cat /var/run/my_process.pid | kill
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
  ;;
  *)
    echo "Usage: manage_my_process {start|stop|restart}"   
esac
