#!/usr/bin/env bash
#script that displays:To infinity and beyond indefinitely; With a sleep 2 in between each iteration; I am invincible!!! when receiving a SIGTERM signal
while [[ 1 -eq 1 ]]
do
	echo To infinity and beyond
	sleep 2
  if trap 15 ; then
    echo I am invincible!!!
  fi
done
